version: '3.9'

services:
  db-mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-net

  app-flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tmdb_app
    environment:
      - API_KEY=${API_KEY}
      - MONGO_IP=db-mongo  # Name of the MongoDB service in docker-compose    
    depends_on:
      - db-mongo
    # ports:
    #   - "5001:5001"
    networks:
      - backend-net
      - frontend-net
  
  reverse-proxy-nginx:
    image: nginx:mainline-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - frontend-net      

networks:
  backend-net:
  frontend-net:

volumes:
  mongo-data: