version: '3.9'

services:
  db-mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - backend_network

  app-flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tmdb_app
    environment:
      - API_KEY=${API_KEY}
      - MONGO_IP=db-mongo  # Name of the MongoDB service in docker-compose    
    depends_on:
      - db-mongo    
    networks:
      - backend_network
      - frontend_network
  
  reverse-proxy-nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"    
    networks:
      - frontend_network
      - ci_network      

networks:
  backend_network:
  frontend_network:
  ci_network:
    external: true

volumes:
  mongo-data: