version: '3.9'

services:
  db-mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - ci_network

  app-flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tmdb_app
    environment:
      - API_KEY=${API_KEY}
      - MONGO_IP=db-mongo  # Name of the MongoDB service in docker-compose    
    depends_on:
      - db-mongo    
    networks:
      - ci_network
  
  reverse-proxy-nginx:
    image: nginx:mainline-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - ci_network      

networks:
  ci_network:
    external: true

volumes:
  mongo-data: