version: '3.9'

services:
  db-mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db    
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "db-mongo", "--eval", "quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - backend_network

  app-flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tmdb_app
    environment:
      - API_KEY=${API_KEY}
      - MONGO_IP=db-mongo  # Name of the MongoDB service in docker-compose
    depends_on:
      - db-mongo        
    networks:
      - backend_network
      - frontend_network
  
  reverse-proxy-nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - app-flask
    ports:
      - "80:80"
    networks:
      - frontend_network
      - ci_network

networks:
  backend_network:
  frontend_network:
  ci_network:
    # external: true

volumes:
  mongo-data: